# Generated by Django 5.1.2 on 2024-11-03 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.FileField(upload_to='documents/')),
                ('caption', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='main.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_submissions', to='main.users'),
        ),
        migrations.AddField(
            model_name='submission',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.users'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=100)),
                ('contact_num', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('profile_img', models.FileField(upload_to='documents/')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_profiles', to='main.users')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='documents/')),
                ('caption', models.TextField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('comments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_posts', to='main.comment')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='main.users')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('theme', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('submission_rules', models.TextField(max_length=100)),
                ('voting_criteria', models.TextField(max_length=100)),
                ('prizes', models.TextField(max_length=100)),
                ('event_banner', models.FileField(upload_to='documents/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('eventCategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventcategory')),
                ('eventType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventtype')),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_submissions', to='main.submission')),
                ('competitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_events', to='main.users')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='main.users')),
                ('judges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judged_events', to='main.users')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_comments', to='main.users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.users'),
        ),
        migrations.AddField(
            model_name='users',
            name='usertype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertype'),
        ),
    ]
