# Generated by Django 5.1.2 on 2024-11-03 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='competitors',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='users_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='users_id',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='submission_id',
            new_name='submission',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventCategory_id',
            new_name='eventCategory',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventType_id',
            new_name='eventType',
        ),
        migrations.RemoveField(
            model_name='event',
            name='submission_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.comment'),
        ),
        migrations.AddField(
            model_name='event',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='event_submissions', to='main.submission'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(blank=True, upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_num',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='suffix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.ImageField(upload_to='submissions/'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertype')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main.user'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='main.user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='main.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='competitors',
            field=models.ManyToManyField(blank=True, related_name='competitor_events', to='main.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judged_events', to='main.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='main.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='main.user'),
        ),
        migrations.AddField(
            model_name='submission',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_submissions', to='main.user'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
