# Generated by Django 5.1.2 on 2024-11-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_comment_users_id_remove_profile_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='dateJoined',
        ),
    ]
