# Generated by Django 5.1.4 on 2024-12-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
