# Generated by Django 5.1.2 on 2024-11-09 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_createdat_user_datejoined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(upload_to='general-post/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_imgs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usertype'),
        ),
    ]
