# Generated by Django 5.1.3 on 2024-12-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('main', '0006_alter_post_photo_alter_profile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('custom_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
