# Generated by Django 5.1.3 on 2024-12-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtoken',
            name='custom_field',
        ),
        migrations.AddField(
            model_name='customtoken',
            name='userToken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='main.user'),
        ),
    ]
