# Generated by Django 5.1.3 on 2024-12-13 05:07

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_customtoken_custom_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtoken',
            name='userToken',
        ),
        migrations.AddField(
            model_name='customtoken',
            name='login_timestamp',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
