# Generated by Django 5.1.3 on 2024-12-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_customtoken_login_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
