# Generated by Django 5.1.3 on 2024-12-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('main', '0013_delete_customtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('userToken', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='main.user')),
            ],
            bases=('authtoken.token',),
        ),
    ]
